name: Build and Security Scan

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: arc-runner-set
    
    #container: 
     # image: docker:20.10.7-dind
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install libcurl4-openssl-dev 
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev -y
        sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev -y
        # You can add more package installations here if needed
        
    - name: Set up R
      uses: r-lib/actions/setup-r@v2.3.1
      with:
        r-version: 4.3.2  # Specify your desired R version

    - name: Install Dependencies
      run: |
        Rscript -e "install.packages('textshaping')"
        Rscript -e "install.packages('curl')"
        Rscript -e "install.packages('targets')"
        Rscript -e "install.packages('futile.logger')" 
        Rscript -e "install.packages('conflicted')"
        Rscript -e "install.packages('remotes')"
        Rscript -e "install.packages('shiny')"
        Rscript -e "install.packages('tidyverse')"
        Rscript -e "install.packages('cyclocomp',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('xml2',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('knitr',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('digest',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('glue',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('backports',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('rex',repos='http://cran.us.r-project.org')"
        # Add more package installations as needed
        
    - name: Install lintr
      run: |
        Rscript -e "install.packages('lintr',repos='http://cran.us.r-project.org')"
        #Rscript -e "install.packages('lintr')"
       
    - name: Run lintr
      run: |
        Rscript -e 'lintr::lint_package()'

    - name: Run R Script
      run: |
        Rscript matrix.R 

    - name: Update Grype Database
      run: |
        docker run --rm  anchore/grype db update
         docker run --rm  anchore/grype db status
    
    - name: Scan current project
      uses: anchore/scan-action@v3.6.4
      with:
        path: ${{ github.workspace }}  
        
        #"."       
    - name: Install Syft
      run: |
        #sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin'
        #syft version  
        #sudo chmod +x /usr/local/bin/syft
        #syft . -o json > syft-output.json
        docker run --privileged --rm -v $(pwd):/src anchore/syft /src -o json > syft-output.json
      
    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
