name: Build and Security Scan

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: arc-runner-set

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install libcurl4-openssl-dev 
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev -y
        sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev -y
        # You can add more package installations here if needed
        
    - name: Set up R
      uses: r-lib/actions/setup-r@v2.3.1
      with:
        r-version: 4.3.2  # Specify your desired R version

    - name: Install Dependencies
      run: |
        Rscript -e "install.packages('textshaping')"
        Rscript -e "install.packages('curl')"
        Rscript -e "install.packages('targets')"
        Rscript -e "install.packages('futile.logger')" 
        Rscript -e "install.packages('conflicted')"
        Rscript -e "install.packages('remotes')"
        Rscript -e "install.packages('shiny')"
        Rscript -e "install.packages('tidyverse')"
        Rscript -e "install.packages('cyclocomp',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('knitr',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('digest',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('glue',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('backports',repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('rex',repos='http://cran.us.r-project.org')"
        # Add more package installations as needed
        
    - name: Install lintr
      run: |
        Rscript -e "install.packages('lintr',repos='http://cran.us.r-project.org')"
        #Rscript -e "install.packages('lintr')"
       
    - name: Run lintr
      run: |
        Rscript -e 'lintr::lint_package()'

    - name: Run R Script
      run: |
        Rscript matrix.R 
    - name: Install Grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      
    - name: Run CVE Scanning with Grype
      run: |
        docker run --rm -v ${{github.workspace}}:/src anchore/grype /src -o json > grype-output.json
        if grep -q '"severity":"Critical"' grype-output.json; then
          echo "Critical vulnerabilities found!"
         exit 1
        fi
    - name: Install Syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      
    - name: Generate SBOM with Syft
      run: docker run --rm -v ${{github.workspace}}:/src anchore/syft /src -o json > sbom.json
      
    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
